GET http://localhost:5002/users

###
POST http://localhost:5002/buku/
Content-Type: application/json

{
    "judul_buku": "cerita rakyat",
    "penerbit": "gramedia",
    "stok": "20"
}

###
POST http://localhost:5002/peminjaman/
Content-Type: application/json

{
    "tanggal_peminjaman": "15/01/2025",
    "tanggal_batas": "15/01/2025",
    "status_peminjaman": "Dipinjam"
}


POST http://localhost:5002/pengembalian/
Content-Type: application/json

{
    "tanggal_pengembalian": "15/01/2025",
    "denda": "1000",
}